#deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-docker-kubernetes-assignment-code
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-docker-kubernetes-assignment-code
  template:
    metadata:
      labels:
        app: spring-docker-kubernetes-assignment-code
    spec:
      containers:
      - name: spring-docker-kubernetes-assignment-code
        image: mohammedadil26/docker-kubernetes-assignment
        ports:
        - containerPort: 8080