apiVersion: v1
kind: Service
metadata:
  name: spring-docker-kubernetes-assignment-code
spec:
  selector:
    app: spring-docker-kubernetes-assignment-code
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer